# -*- coding: utf-8 -*-
"""RL of LCCA & RCCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o776WQRipywKgWO9ViHTyFGyjs0g2QC1
"""

!pip install seaborn
!pip install pydicom scikit-image networkx matplotlib numpy scipy
!pip install scikit-image
!pip install openpyxl
!pip install SimpleITK

import os
import SimpleITK as sitk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from skimage.morphology import skeletonize
from skimage.morphology import remove_small_holes
from skimage import img_as_bool
from scipy.spatial import KDTree
from scipy.ndimage import label
from scipy.ndimage import center_of_mass
import seaborn as sns
from sklearn.cluster import KMeans
import pydicom
from skimage import filters, morphology, measure
from scipy.ndimage import gaussian_filter, binary_closing
import networkx as nx
from skimage.graph import MCP_Geometric
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib.patches as mp

import skimage

import gdown
import zipfile
import os

# https://drive.google.com/file/d/1guzXTbY9OMWSbqRGXyjZnZ3edoI9K7mw/view?usp=sharing
file_id = '1guzXTbY9OMWSbqRGXyjZnZ3edoI9K7mw'

url = f'https://drive.google.com/uc?id={file_id}'

zip_output = 'my_file.zip'

gdown.download(url, zip_output, quiet=False)

extract_dir = './extracted_files'
os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_output, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

from google.colab import drive
!pip install -q gdown
import gdown
!apt-get install unrar -y

# "https://drive.google.com/file/d/1M9Lt6Ivhqccernc42qo-MvgifkNHcJjo/view?usp=sharing"
# "https://drive.google.com/drive/folders/1Qy3L8w3CLYurnraK6Nb3DUTLePu8ssRY?usp=sharing"

drive.mount('/content/drive')
file_id = "1M9Lt6Ivhqccernc42qo-MvgifkNHcJjo"
url = f"https://drive.google.com/uc?export=download&id={file_id}"

# drive.mount('/content/drive')
# file_id = "1Qy3L8w3CLYurnraK6Nb3DUTLePu8ssRY"
# url = f"https://drive.google.com/uc?export=download&id={file_id}"


gdown.download(url, "file.rar", quiet=False)

!pip install -q gdown

!gdown --folder "https://drive.google.com/file/d/1guzXTbY9OMWSbqRGXyjZnZ3edoI9K7mw/view?usp=sharing"
!unrar x file.rar

input_path = "/content/extracted_files/1170927769/DICOM/20250531/223757"
# input_path = "/content/drive/MyDrive/Stroke/161213"
# input_path = "/content/Data/1273774353/DICOM/20250528/231921"
input_path = input_path
output_path = "/content/output"

os.makedirs(output_path, exist_ok=True)

if os.path.exists(input_path):
    print("Files in input_path:", os.listdir(input_path))
else:
    raise FileNotFoundError(f"Input directory {input_path} does not exist.")

reader = sitk.ImageSeriesReader()
dicom_names = reader.GetGDCMSeriesFileNames(input_path)
if not dicom_names:
    raise FileNotFoundError("No DICOM files found in the directory.")
reader.SetFileNames(dicom_names)
img = reader.Execute()
img_array = sitk.GetArrayFromImage(img)
print("Image size:", img.GetSize())
print("Image spacing:", img.GetSpacing())
print("Pixel type of input image:", img.GetPixelIDTypeAsString())

plt.imshow(img_array[0, :, :], cmap='gray')
ax = plt.gca()
ax.xaxis.set_major_locator(ticker.MultipleLocator(50))
ax.yaxis.set_major_locator(ticker.MultipleLocator(50))
ax.tick_params(axis='x', labelsize=8, labelrotation=45)
ax.tick_params(axis='y', labelsize=8)
plt.show()

def ensure_minimum_size(image, min_size=4):
    size = image.GetSize()
    spacing = image.GetSpacing()
    new_size = [max(s, min_size) for s in size]
    if size == tuple(new_size):
        return image
    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputSpacing(spacing)
    resampler.SetSize(new_size)
    resampler.SetInterpolator(sitk.sitkLinear)
    resampler.SetOutputOrigin(image.GetOrigin())
    resampler.SetOutputDirection(image.GetDirection())
    return resampler.Execute(image)

img = ensure_minimum_size(img)
img_array = sitk.GetArrayFromImage(img)
print("Image size after resampling:", img.GetSize())

print("Pixel type before processing:", img.GetPixelIDTypeAsString())
if img.GetNumberOfComponentsPerPixel() > 1:
    print("Converting multi-component image to single-component.")
    img = sitk.VectorMagnitude(img)
img = sitk.Cast(img, sitk.sitkFloat32)
print("Pixel type after cast:", img.GetPixelIDTypeAsString())

enhanced_img=img

otsu_filter = sitk.OtsuThresholdImageFilter()
otsu_filter.SetInsideValue(0)
otsu_filter.SetOutsideValue(1)
binary_img = otsu_filter.Execute(enhanced_img)

kernel_radius = 2
binary_img = sitk.BinaryMorphologicalClosing(binary_img, [kernel_radius]*3)
connected_filter = sitk.ConnectedComponentImageFilter()
labeled_img = connected_filter.Execute(binary_img)
stats_filter = sitk.LabelShapeStatisticsImageFilter()
stats_filter.Execute(labeled_img)

labels = stats_filter.GetLabels()
sizes = [stats_filter.GetNumberOfPixels(l) for l in labels]
largest_label = labels[np.argmax(sizes)]
refined_img = (labeled_img == largest_label)


refined_array = sitk.GetArrayFromImage(refined_img)

bw = img_as_bool(refined_array*255)
out=remove_small_holes(bw, 140)

depth, height, width = bw.shape
skeleton_3d = np.zeros_like(bw, dtype=bool)
for i in range(depth):
    skeleton_3d[i] = skeletonize(out[i])

skeleton_array=skeleton_3d
skeleton_img = sitk.GetImageFromArray(skeleton_array.astype(np.uint8))
skeleton_img.CopyInformation(img)

import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d
from scipy.signal import find_peaks

def turning_angles(points):
    """
    points: (N,2) ordered polyline
    returns:
      angles: (N-1,) angle of each segment in radians (atan2)
      dangles: (N-2,) signed turning angle between consecutive segments (radians, wrapped to (-pi,pi])
      seg_lengths: (N-1,) euclidean lengths of segments
    """
    pts = np.asarray(points, dtype=float)
    diffs = np.diff(pts, axis=0)               # (N-1,2)
    seg_lengths = np.linalg.norm(diffs, axis=1)
    angles = np.arctan2(diffs[:,1], diffs[:,0])  # (N-1,)
    # angle differences between consecutive segments
    raw = np.diff(angles)                        # (N-2,)
    # wrap to (-pi, pi]
    dangles = (raw + np.pi) % (2*np.pi) - np.pi
    return angles, dangles, seg_lengths

def find_turns(points, sigma=0.0, deg_threshold=20.0, min_distance=1):
    """
    Detect turning points in an ordered polyline.
    - sigma: gaussian smoothing applied to angles (0=no smoothing)
    - deg_threshold: turning threshold in degrees (absolute)
    - min_distance: minimum peak distance in number of turning-angle samples
    Returns: indices of points (in original points array) considered turning points.
      Note: turning angles are defined for interior points p[1..N-2].
    """
    angles, dangles, seg_lengths = turning_angles(points)
    # optional smoothing (on angles before differencing or on dangles)
    # if sigma > 0:
    #     # smooth angles then recompute dangles to avoid wrap problems use sin/cos smoothing instead
    #     a = angles
    #     # smooth sin and cos separately to preserve circular nature
    #     s = gaussian_filter1d(np.sin(a), sigma)
    #     c = gaussian_filter1d(np.cos(a), sigma)
    #     a_smooth = np.arctan2(s, c)
    #     dangles = np.diff(a_smooth)
    #     dangles = (dangles + np.pi) % (2*np.pi) - np.pi


    # curvature-like measure: absolute turning per unit length (optional)
    # use average of adjacent segment lengths to scale
    avg_len = (seg_lengths[:-1] + seg_lengths[1:]) / 2.0
    curvature = np.abs(dangles) / (avg_len + 1e-12)  # avoid div by zero

    # choose detection method: threshold on absolute angle or on curvature
    degs = np.degrees(np.abs(dangles))
    # primary candidates: where angle exceeds threshold
    cand_mask = degs >= deg_threshold

    # refine using peaks on degs or curvature
    peaks, props = find_peaks(degs, distance=min_distance, height=deg_threshold)
    # peaks array indexes into dangles (i.e. interior points corresponding to original index = peaks+1)
    # convert to indices in original points array: turning at point i corresponds to original point index = i+1
    turning_point_indices = (peaks + 1).tolist()  # interior points
    return {
        'angles': angles,
        'dangles': dangles,
        'deg_abs': degs,
        'curvature': curvature,
        'candidates_mask': cand_mask,
        'turning_point_indices': turning_point_indices
    }

#%%
# image=np.zeros([1017,1017],np.uint8)
# image[:650,450:]=skeleton_array[0,:650,450:]
# pts=np.argwhere(image)

#%%
# Make image canvas based on actual skeleton slice size (safe)
slice0 = skeleton_array[0]            # (H, W)
H, W = slice0.shape
# Option A: use exact same size
image = np.zeros((H, W), dtype=np.uint8)
r_end = min(650, H)
c_start = 450
# ensure c_start < W
if c_start >= W:

    c_start = 0
image[:r_end, c_start:] = slice0[:r_end, c_start:].astype(np.uint8)
pts = np.argwhere(image)


res = find_turns(pts, sigma=0.0, deg_threshold=49.5, min_distance=1)
turns = res['turning_point_indices']  # indices in pts of turning points
points=pts[turns]

fig, ax = plt.subplots()

# Show image on the axis
ax.imshow(image)

# Plot points over the same axis
x_coords = [p[0] for p in points]
y_coords = [p[1] for p in points]

ax.scatter(y_coords, x_coords, color='blue', s=0.1, marker='o')

ax.set_title("Extracted Points Overlayed on Image")
ax.axis("off")
plt.show()
#%%

max_slices_to_show = 37

total_slices = img_array.shape[0]
n_slices = min(max_slices_to_show, total_slices)

pts_per_slice = [np.sum(img_array[i]) for i in range(n_slices)]

cols_grid = 6
rows_grid = int(np.ceil(n_slices / cols_grid))

fig, axes = plt.subplots(rows_grid, cols_grid,
                         figsize=(cols_grid * 10.0, rows_grid * 10.0))

if rows_grid == 1 and cols_grid == 1:
    axes = np.array([axes])
else:
    axes = axes.flatten()

for i in range(n_slices):
    ax = axes[i]
    ax.imshow(img_array[i], cmap='gray', vmin=0, vmax=1)
    ax.set_title(f'Slice {i}  ({pts_per_slice[i]})', fontsize=7)
    ax.axis('off')

for i in range(n_slices, len(axes)):
    axes[i].axis('off')

plt.suptitle(f'Pure Skeleton (First {n_slices} Slices)\n',
             fontsize=12, fontweight='bold', y=1.02)

plt.tight_layout()
plt.show()

"""**Measuring the RL of LCCA and RCCA**

---


"""

SLICE_IDX = 1
# skel1 = skeleton_3d[SLICE_IDX]
skel1 = img_array[SLICE_IDX]

VIEW = {
    "LCCA": {"r_lo": 250, "r_hi": 670, "c_lo": 300, "c_hi": 550},
    "RCCA": {"r_lo": 250, "r_hi": 670, "c_lo": 300, "c_hi": 550},
}

def show_roi_on_skeleton(r_min, r_max, c_min, c_max, vessel="LCCA", label=""):
    v = VIEW[vessel]
    fig, ax = plt.subplots(figsize=(7, 8))
    ax.imshow(skel1[v["r_lo"]:v["r_hi"], v["c_lo"]:v["c_hi"]],
              cmap='gray', extent=[v["c_lo"], v["c_hi"], v["r_hi"], v["r_lo"]])


    rect = mp.Rectangle((c_min, r_min), c_max - c_min, r_max - r_min,
                         lw=2, edgecolor='yellow', facecolor='none', ls='--')
    ax.add_patch(rect)

    ax.set_title(f"{vessel} — slice {SLICE_IDX}  |  "
                 f"row:[{r_min},{r_max}]  col:[{c_min},{c_max}]  {label}", fontsize=10)
    ax.set_xlabel("col (x)")
    ax.set_ylabel("row (y)")
    plt.tight_layout()
    plt.show()


# LCCA
show_roi_on_skeleton(r_min=270, r_max=660, c_min=345, c_max=410, vessel="LCCA")

# RCCA
show_roi_on_skeleton(r_min=270, r_max=660, c_min=480, c_max=545, vessel="RCCA")

SLICE_IDX = 1

spacing_arr = np.array(img.GetSpacing())[::-1]
spacing_yx  = (spacing_arr[1], spacing_arr[2])

RCCA_ROI = {
    "row_min": 150,
    "row_max": 660,
    "col_min": 340,
    "col_max": 460,
}


END_POINT = (655, 355)
START_POINT   = (170, 430)


def get_skeleton_in_roi(skel_slice, roi):
    r0,r1,c0,c1 = roi["row_min"],roi["row_max"],roi["col_min"],roi["col_max"]
    pts = np.argwhere(skel_slice[r0:r1, c0:c1])
    pts[:,0] += r0;  pts[:,1] += c0
    return pts


def path_between_points(pts_px, start_rc, end_rc, sp_yx):

    if len(pts_px) < 3:
        return None

    pts_mm = pts_px * np.array([sp_yx[0], sp_yx[1]])

    G = nx.Graph()
    for i, p in enumerate(pts_mm):
        G.add_node(i, pos=p, px=pts_px[i])

    tree = KDTree(pts_px)
    for i in range(len(pts_px)):
        for j in tree.query_ball_point(pts_px[i], np.sqrt(2)):
            if j > i:
                G.add_edge(i, j, weight=np.linalg.norm(pts_mm[i]-pts_mm[j]))

    start_mm = np.array([start_rc[0]*sp_yx[0], start_rc[1]*sp_yx[1]])
    end_mm   = np.array([end_rc[0]*sp_yx[0],   end_rc[1]*sp_yx[1]])

    dists_start = np.linalg.norm(pts_mm - start_mm, axis=1)
    dists_end   = np.linalg.norm(pts_mm - end_mm,   axis=1)

    node_start = int(np.argmin(dists_start))
    node_end   = int(np.argmin(dists_end))

    print(f"  Closest node to START: px={pts_px[node_start]}")
    print(f"  Closest node to END  : px={pts_px[node_end]}")

    try:
        path_nodes = nx.shortest_path(G, node_start, node_end, weight='weight')
    except nx.NetworkXNoPath:
        print("Error")
        return None

    path_mm = np.array([G.nodes[i]['pos'] for i in path_nodes])
    return path_mm


def compute_RL_full(path_mm):
    if path_mm is None or len(path_mm) < 3:
        return {}
    diffs   = np.diff(path_mm, axis=0)
    seg_len = np.linalg.norm(diffs, axis=1)
    L  = float(seg_len.sum())
    D  = float(np.linalg.norm(path_mm[-1] - path_mm[0]))
    RL = L / D if D > 0 else np.nan

    tang = diffs / (np.linalg.norm(diffs, axis=1, keepdims=True) + 1e-12)
    dot  = np.clip((tang[:-1]*tang[1:]).sum(1), -1, 1)
    angs = np.arccos(dot)
    SOAM = float(angs.sum())
    avg_s     = (seg_len[:-1]+seg_len[1:])/2.0
    curv      = angs/(avg_s+1e-12)
    inflections = int(np.sum(np.abs(np.diff(np.sign(np.diff(angs))))>0))
    ICM = inflections/L if L>0 else np.nan

    return dict(
        Path_Length_mm  = round(L,  3),
        Chord_Length_mm = round(D,  3),
        Relative_Length = round(RL, 4),
        SOAM_deg        = round(float(np.degrees(SOAM)), 2),
        ICM             = round(ICM, 6),
        Mean_Curvature  = round(float(curv.mean()), 6),
        Inflection_Count= inflections,
    )



skel1   = skeleton_3d[SLICE_IDX]
pts_raw = get_skeleton_in_roi(skel1, RCCA_ROI)
print(f"points skeleton  ROI: {len(pts_raw)}")

path_mm = path_between_points(pts_raw, START_POINT, END_POINT, spacing_yx)

if path_mm is not None:
    res = compute_RL_full(path_mm)

    print("\n" + "="*50)
    print("  RCCA — Relative Length")
    print("="*50)
    print(f"  Actual Length  (L) : {res['Path_Length_mm']:.2f} mm")
    print(f"  Chord Length   (D) : {res['Chord_Length_mm']:.2f} mm")
    print(f"  Relative Length: {res['Relative_Length']:.4f}")
    print(f"  SOAM           : {res['SOAM_deg']:.2f}°")
    print(f"  ICM            : {res['ICM']:.6f}")
    print("="*50)

    roi = RCCA_ROI
    r0,r1,c0,c1 = roi["row_min"],roi["row_max"],roi["col_min"],roi["col_max"]
    pad  = 40
    r_lo = max(0,r0-pad); r_hi = min(skel1.shape[0],r1+pad)
    c_lo = max(0,c0-pad); c_hi = min(skel1.shape[1],c1+pad)

    fig, axes = plt.subplots(1, 2, figsize=(14, 10))

    for ax_idx, (bg, title) in enumerate([
        (skel1,                 "On Skeleton"),
        (img_array[SLICE_IDX], "On Real Image"),
    ]):
        ax = axes[ax_idx]
        ax.imshow(bg[r_lo:r_hi, c_lo:c_hi], cmap='gray',
                  extent=[c_lo,c_hi,r_hi,r_lo])


        ax.add_patch(mp.Rectangle((c0,r0),c1-c0,r1-r0,
                                   lw=2,edgecolor='yellow',
                                   facecolor='none',ls='--'))

        path_px = path_mm / np.array([spacing_yx[0], spacing_yx[1]])

        ax.plot(path_px[:,1], path_px[:,0], '-',
                color='limegreen', lw=2.5,
                label=f"L={res['Path_Length_mm']:.1f} mm")
        ax.plot([path_px[0,1], path_px[-1,1]],
                [path_px[0,0], path_px[-1,0]],
                '--', color='cyan', lw=2,
                label=f"D={res['Chord_Length_mm']:.1f} mm")

        ax.scatter([START_POINT[1]], [START_POINT[0]],
                   c='lime', s=120, zorder=7, marker='o', label='START')
        ax.scatter([END_POINT[1]],   [END_POINT[0]],
                   c='red',  s=120, zorder=7, marker='s', label='END')

        txt = (f"L = {res['Path_Length_mm']:.2f} mm\n"
               f"D = {res['Chord_Length_mm']:.2f} mm\n"
               f"RL = {res['Relative_Length']:.4f}\n"
               f"SOAM = {res['SOAM_deg']:.1f}°")
        ax.text(0.02,0.98,txt,transform=ax.transAxes,fontsize=9,
                va='top',fontfamily='monospace',color='white',
                bbox=dict(boxstyle='round',facecolor='black',alpha=0.8))

        ax.set_xlim(c_lo,c_hi); ax.set_ylim(r_hi,r_lo)
        ax.set_title(f"RCCA — {title}", fontsize=11, fontweight='bold')
        ax.legend(fontsize=8, loc='lower right')

    plt.suptitle(f"RCCA RL={res['Relative_Length']:.4f}  |  "
                 f"L={res['Path_Length_mm']:.2f}  D={res['Chord_Length_mm']:.2f} mm",
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    out_png = os.path.join(output_path, f"RCCA_RL_slice{SLICE_IDX}.png")
    plt.savefig(out_png, dpi=200, bbox_inches='tight')
    plt.show()